### ISSUE TITLE
Fail to load data!

### ISSUE THREAD

**Issue by skytguuu** [lidaof/g3d#35] opened 2022-06-28 15:52 UTC
Hi,

Thanks for your developed tools "g3d". Recently, I tried to use washU epigenome browser to visulize the 3D genome. However, I met the g3d format question.  As your mentioned, I prepared the data format as : 6 columns with chromosome, start position, end position, X, Y,
Z.  And I tried followed the command "g3dtools load ../test/test.g3d.bed.gz -o ../testOut/test -s 2,3,4,5,6,7,8,9,10" to run, but it failed. The error reported the  "invalid choice: 'load' (choose from 'dump', '3dg', 'meta', 'query')". 

Then, I tried to use another command "g3dtools 3dg ../test/GSM3271347_gm12878_01.impute3.round4.clean.3dg.txt.gz -o ../testOut/GSM3271347_gm12878_01.impute3.round4.clean -s 2,3,4,5,6,7,8,9,10" to run my data. It worked until I changed the data with the format : "chr,start,X,Y,Z". But the result showed nothing in the washU epigenome browser. 

I dont know what's the problem? Could you give me a hand?

My data is as followed:
chrX    4920000 4940000 0.7752011702587246      -0.005422823771527644   0.028275711216707192
chrX    4940000 4960000 0.784200243785972       0.047906083346667114    0.07900583351871773
chrX    4960000 4980000 0.7574346063475412      -0.025529809687840972   -0.009058123316518528
...

Thanks!
Best,
Garen

**Comment by lidaof** [comment] 2022-06-28 19:35
Hi Garen @skytguuu, thanks for your interest. It's very wried that load is not recognized as a sub command...never seen this before...possible you can send me your `test.g3d.bed.gz` (lidaof@gmail.com) so I can troubleshoot? Thank you!

**Comment by skytguuu** [comment] 2022-06-29 03:47
Hi, @lidaof 

Thanks for your quick reply. I have updated the test_g3d_input.bed (https://drive.google.com/file/d/1kBoFmhnwkN3W2Q_ajRP8bWEfUENBgmAn/view?usp=sharing), and the result test.g3d (https://drive.google.com/file/d/12_N59cm4zHS4l508GvNoe5W7dbN6WTaZ/view?usp=sharing) on the google drive.

Thanks!

**Comment by skytguuu** [comment] 2022-07-01 02:37
Hi @lidaof , I am appreciated for your help. I have changed the format with removing the third columns. However, it still failed because of the "load" command. My command is :g3dtools load test_3d.bed -o test.g3d -s 2,3,4,5,6,7,8,9,10, it reported the error that "g3dtools: error: invalid choice: 'load' (choose from 'dump', '3dg', 'meta', 'query')". I don't know why the command is failed?

Thanks!
Best

**Comment by lidaof** [comment] 2022-07-01 03:03
Hi @skytguuu very weird, can you do a `pip install g3dtools` again? i was able to process your file...

**Comment by skytguuu** [comment] 2022-07-01 03:15
Hi @lidaof , I have tried again, but it still failed.
![image](https://user-images.githubusercontent.com/25957174/176816368-e894e940-64e3-4486-aa85-7b4d57deb1c1.png)

Should I uninstall the g3dtools, then install it again?
Thanks

**Comment by lidaof** [comment] 2022-07-01 03:17
so strange...i see the version is also right.....if you just type g3dtools can you see the load subcommand show up?

<img width="910" alt="image" src="https://user-images.githubusercontent.com/102806/176816657-4bdc06f7-93af-4969-a1da-1aa8c925efa9.png">

**Comment by skytguuu** [comment] 2022-07-01 04:08
Hi @lidaof , g3dtools showed as followed:
![image](https://user-images.githubusercontent.com/25957174/176821625-c29f0b99-db12-40ed-96e5-4ab3b0433a75.png)

Thanks!

**Comment by lidaof** [comment] 2022-07-01 04:12
apparently `load` is missing....not sure why, are you using python3? you can see from https://github.com/lidaof/g3d/blob/master/g3dtools/g3dtools there is `load` in it..
i just tried pip install g3dtools on a new server which works on your file....

another approach is download the repo https://github.com/lidaof/g3d/ and go to g3dtools folder run `python3 g3dtools`, what's the output then?

**Comment by skytguuu** [comment] 2022-07-01 04:25
I used python3.7, when I tried to run python3 g3dtools, it showed the load parameter.
![image](https://user-images.githubusercontent.com/25957174/176823177-f0ee31b5-7a01-4bed-a172-c1a64f5db925.png)

**Comment by skytguuu** [comment] 2022-07-01 08:02
I used the command: python g3dtools load ~/mnt1/Chip-seq/ChIP_process/FGSC_SSC_project/chrX/fgsc_3D.bed -o test.g3d -s 2,3,4,5,6,7,8,9,10, but the result cannot show anything in the washU epigenome browser. I have updated the result on the google drive(python g3dtools load ~/mnt1/Chip-seq/ChIP_process/FGSC_SSC_project/chrX/fgsc_3D.bed -o test.g3d -s 2,3,4,5,6,7,8,9,10).

**Comment by lidaof** [comment] 2022-07-02 02:32
Hi @skytguuu sorry for the delay. the files on google drive seems not updated, I download both of them seems same as previous ones. when you able to generate the .g3d file, can you try upload it as local file? please see https://eg.readthedocs.io/en/latest/local.html. I suspect you might put file on a web server which didn't enable CORS (https://eg.readthedocs.io/en/latest/tracks.html#configure-your-webserver-to-enable-cors).

**Comment by skytguuu** [comment] 2022-07-02 03:30
Hi @lidaof , I followed the instruction to load the g3d data in the washu browser with local track. But it showed nothing. I updated the google drive again (https://drive.google.com/file/d/12_N59cm4zHS4l508GvNoe5W7dbN6WTaZ/view?usp=sharing). Could you check it? I don't know what's wrong?
![image](https://user-images.githubusercontent.com/25957174/176985071-b15bd2b8-bbd5-4e97-88d8-f3641917452a.png)

Thanks!

**Comment by lidaof** [comment] 2022-07-02 03:51
Hi @skytguuu i cannot query this file, can you send the original bed file? Can you try this attached file as well? after download remove it to 3.g3d, thanks.
[3.g3d.zip](https://github.com/lidaof/g3d/files/9032377/3.g3d.zip)

**Comment by skytguuu** [comment] 2022-07-02 04:18
I cannot unzip the attached file 3.g3d.zip.  I have used another drive to store the data. Please check it:
https://data.cyverse.org/dav-anon/iplant/home/tguuu/test.g3d.g3d
https://data.cyverse.org/dav-anon/iplant/home/tguuu/1.bed

**Comment by lidaof** [comment] 2022-07-02 13:23
Hi @skytguuu the first 2 columns should be `chr<TAB>start`, can you also remove those lines with nan?
<img width="758" alt="image" src="https://user-images.githubusercontent.com/102806/177002641-adcf715c-00cc-4b2e-9a90-e6e57317b881.png">

by the way, the 3.g3d.zip is not  zip file, github doesn't allow upload .g3d file so I add an .zip after it, rename it and remove .zip should work

**Comment by skytguuu** [comment] 2022-07-03 12:13
Hi, @lidaof 

I am appreciated for your help. After I reinstall the g3dtools, it should the load command. It worked well in the browser. 

Thanks!
Best

**Comment by lidaof** [comment] 2022-07-03 12:56
great! glad it worked out. i am closing this issue and feel free to open new ones.
Thank you @skytguuu!

**Closed by lidaof** 2022-07-03 12:56 UTC

**Comment by hanshanmengqi** [comment] 2024-01-24 15:47
> Hi @skytguuu i cannot query this file, can you send the original bed file? Can you try this attached file as well? after download remove it to 3.g3d, thanks. [3.g3d.zip](https://github.com/lidaof/g3d/files/9032377/3.g3d.zip)

Hello @lidaof, 
Thanks for your tool, it's really beautiful.
I've tried different files but both failed. I also tried 3.g3d.zip you showed in the above reply.
![image](https://github.com/lidaof/g3d/assets/93769611/6eb6ca08-6506-426d-8255-b9b6fd79453c)
Could you please take a look of this problem. 
The attachments are my files(for g3d.zip just remove .zip will be fine.)


Thank you for your time!
Han
[test.xls](https://github.com/lidaof/g3d/files/14040597/test.xls)
[test.g3d.zip](https://github.com/lidaof/g3d/files/14040600/test.g3d.zip)

**Comment by lidaof** [comment] 2024-01-24 16:10
Hi @hanshanmengqi ,

I was not able to open your excel file
<img width="246" alt="image" src="https://github.com/lidaof/g3d/assets/102806/f32d69cb-952d-4f1c-bb9a-59e860b45c72">

But the g3d file after I remove the .zip extension, it can be loaded into the browser:
<img width="800" alt="image" src="https://github.com/lidaof/g3d/assets/102806/6bbbee4a-0282-4266-9acd-d29e8fed23e0">

The file format is correct when I convert to bed format:
```
chr1    0       114.625 17.4985 -22.453 shared
chr1    200000  106.48349999999999      31.3425 3.085   shared
chr1    400000  97.736  30.4135 -4.0565 shared
chr1    600000  110.5985        30.502000000000002      -12.0325        shared
chr1    800000  93.85050000000001       33.016  -14.291500000000001     shared
chr1    1000000 110.485 46.2905 -11.938 shared
chr1    1200000 108.16399999999999      50.574  -0.6749999999999999     shared
chr1    1400000 113.769 62.997  -3.9574999999999996     shared

```

you might need to `git pull` the latest browser code which is v54.0.4

**Comment by hanshanmengqi** [comment] 2024-01-24 16:49
@lidaof  Thank you so much for your swift reply!
It worked when I used the v54.0.4 browser(https://epigenomegateway.wustl.edu/browser/).

Best,
Han

**Comment by lidaof** [comment] 2024-01-24 17:04
Thank you Han for the feedback!

**Comment by hanshanmengqi** [comment] 2024-01-31 14:35
Hello @lidaof ,
Could you please give me the link to git pull v54.0.4.
I just found V53.6.3 in https://github.com/lidaof/eg-react.

Best,
Han

**Comment by lidaof** [comment] 2024-01-31 15:10
Hi @hanshanmengqi you can just git pull this same repo, if you check https://github.com/lidaof/eg-react/blob/master/frontend/package.json it says 54.0.4. Thank you!

**Comment by hanshanmengqi** [comment] 2024-01-31 15:58
Thank you for your prompt reply!

Best,
Han

**Comment by hanshanmengqi** [comment] 2024-01-31 16:41
Sorry to disturbing again.

I have pulled the latest version, updateed nodejs and npm but I have an error when I want to start the frontend as shown below:

**_# npm -v
10.4.0

# npm install
# washu/eg-react/frontend
# npm start

> [epgg@54.0.4](mailto:epgg@54.0.4) start
> react-app-rewired start

Failed to compile.

Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[2] has an unknown property 'query'. These properties are valid:
   object { assert?, compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, issuerLayer?, layer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, scheme?, sideEffects?, test?, type?, use? }
   -> A rule description with conditions and effects for modules._**

Could you take a look at this if you feel free?

Best,
Han

**Comment by lidaof** [comment] 2024-01-31 16:59
Hi @hanshanmengqi no worries, feel free to ask anytime!

Not sure if it caused by some package issue...
can you try download the working version (which i zipped from my computer) from https://wangftp.wustl.edu/~dli/test/frontend.zip
after download and decompressed, go the folder, type `npm start`, see if it works...
 if you are using node v18, type `export NODE_OPTIONS=--openssl-legacy-provider` before `npm start`

**Comment by lidaof** [comment] 2024-03-07 15:23
Hi @hanshanmengqi i guess the reason of slow is probably due to the web server hosting the track data, can you check if your server's load is high? or you can try restart the web services.
Hope this helps!
